package com.foodora.repository;

import com.foodora.countryapp.models.Country;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Interface defining the methods in the CountryRepository implementation
 * which will be generated by spring as it is annotated with @Repository
 */
@Repository
public interface CountryRepository extends CrudRepository<Country,Integer> {

//  the names of the functions define the actual query with the benefit of hibernate/spring
    List<Country> findCountriesByNameIsContainingIgnoreCase(String name);
    List<Country> findAll();
    List<Country> findCountriesByCodeIsContainingIgnoreCase(String code);
}
